"""
stark_chirp.py
==============

Physically-motivated chirp seeds: track the AC-Stark shift instead of averaging it.

Why a chirp helps
-----------------
The AC-Stark shift of the |01> <-> |10> transition scales as |eta(t)|^2. With the
Hann envelope the sweeps use, S(t) = cos^2(pi u / 2) in the normalized gate time
u = 2t/t_g - 1, so::

    |eta(t)|^2 / eta_pk^2 = cos^4(pi u / 2)

which sweeps 0 -> 1 -> 0 across the gate. A CONSTANT pump offset (``wp_offset_GHz``)
can only cancel the time-AVERAGE of that shift; the drive is then off-resonant at
every other instant. A chirp delta(t) proportional to -|eta(t)|^2 follows the
resonance as it moves.

The key structural fact
-----------------------
``cos^4(pi u / 2) = 3/8 + (1/2) cos(pi u) + (1/8) cos(2 pi u)`` is EVEN in u, so its
Legendre expansion contains only even terms:

    ====  ===========  ==========  ==================
    k     a_k          a_k / a_0   closed form
    ====  ===========  ==========  ==================
    0      0.375000     1.000000   3/8
    2     -0.712415    -1.899772   -225 / (32 pi^2)
    4      0.500397     1.334393
    6     -0.207850    -0.554267
    8      0.051776     0.138069
    ====  ===========  ==========  ==================

Two consequences worth internalising:

* ``a_0 = 3/8`` independently reproduces the Hann relation <eta^2> = 0.375 eta_pk^2
  documented in ``find_stark_resonance.operating_eta`` -- a free cross-check that the
  normalization conventions line up.
* ``c_0`` is EXACTLY equivalent to a constant pump offset (a constant chirp is a
  retuned carrier; see ``envelope.Chirp`` and ``test_constant_chirp_equals_offset_rad``).
  So the leading genuinely-NEW degree of freedom is ``c_2``, not ``c_1``. A linear
  chirp is the wrong first guess: the shape being tracked is even, and a linear term
  is odd.

Because ``s * a_0 = 0.375 s`` is precisely the pulse-averaged shift that a
calibration map already measures as its optimum ``wp_offset_GHz``, the whole seed
collapses to a SINGLE scalar::

    c_k = (delta_stark_GHz / 0.375) * a_k   for k >= 2,      c_0 := 0

or, memorably, ``c_2 = -1.900 * delta_stark`` and ``c_4 = +1.334 * delta_stark``.

Truncation
----------
Measured relative L2 error of the truncated shape (not a guess -- reproduced by
``test_hann_stark_legendre_reconstructs_the_shape``):

    degree 2: 33.8%   degree 4: 11.3%   degree 6: 2.4%   degree 8: 0.32%

Degree 4 is the default: it leaves TWO free coefficients after c_0 is pinned and the
odd terms drop out, which is a tractable search space, and the seed only has to land
in the right basin -- the optimizer refines from there. Raise to 6 when using the
seed open-loop, without a subsequent optimization.

This module is deliberately free of matplotlib and of any solver import, so
``grape`` can use it without dragging in the plotting stack.
"""
from __future__ import annotations

from typing import Any, Dict, Optional, Sequence

import numpy as np

#: Legendre coefficients a_k of cos^4(pi u / 2), k = 0 .. 8 (odd terms vanish).
#: Generated by Gauss-Legendre projection; pinned by a test against the closed forms
#: a_0 = 3/8 and a_2 = -225/(32 pi^2).
HANN_STARK_LEGENDRE: np.ndarray = np.array([
    0.375000000000000,      # a_0 = 3/8, exactly
    0.0,                    # a_1 = 0 by parity (the shape is even in u)
    -0.712414572485201,     # a_2 = -225 / (32 pi^2), exactly
    0.0,                    # a_3
    0.500397358312571,      # a_4
    0.0,                    # a_5
    -0.207850229644700,     # a_6
    0.0,                    # a_7
    0.051775701660015,      # a_8
])

#: a_0: the pulse-averaged value of cos^4(pi u / 2). Also the Hann <eta^2> factor.
HANN_MEAN_FACTOR: float = 0.375


def shape_stark_legendre(shape_fn, degree: int = 8) -> np.ndarray:
    """Legendre coefficients of an ARBITRARY normalized Stark-tracking shape.

    The generalization of :data:`HANN_STARK_LEGENDRE`, which is the special case
    ``shape_fn(u) = cos^4(pi u / 2)`` -- the Hann envelope squared. Recursive DRAG
    needs a base shape with more vanishing end derivatives than a Hann has
    (:class:`envelope.SinePowerRamp`), and its ``|eta(u)|^2`` is a different function,
    so the tabulated Hann array stops applying the moment that shape is selected.

    The quadrature is exact for any smooth `shape_fn`; the TRUNCATION at `degree` is
    the only approximation, and it is the same one the Hann table makes.

    Parameters
    ----------
    shape_fn : callable
        ``u -> |eta(u)|^2 / eta_peak^2`` on ``[-1, 1]``, vectorized over `u`.
    degree : int, default 8
        Highest Legendre order to keep.

    Returns
    -------
    ndarray
        ``a_0 .. a_degree``, with odd terms zeroed (the envelope is symmetric about
        mid-gate, so they vanish by parity; zeroing keeps that exact rather than
        leaving quadrature dust).
    """
    from numpy.polynomial import legendre as L
    n_quad = max(2 * int(degree) + 8, 32)
    u, w = np.polynomial.legendre.leggauss(n_quad)
    y = np.asarray(shape_fn(u), dtype=float)
    a = np.array([(2 * k + 1) / 2.0 * np.sum(w * y * L.legval(u, np.eye(k + 1)[k]))
                  for k in range(int(degree) + 1)])
    a[1::2] = 0.0
    return a


def shape_mean_factor(shape_fn) -> float:
    """Pulse-averaged ``shape_fn``, i.e. its ``a_0``. 0.375 for a Hann."""
    return float(shape_stark_legendre(shape_fn, degree=0)[0])


#: Weightings for :func:`stark_moments`. ``"rabi"`` is the DERIVED one and the
#: default; ``"uniform"`` (average over time) and ``"coupling"`` (weight by the iSWAP
#: rate ``g ~ |eta|``) are the two plausible guesses that preceded it, kept because
#: they bracket it and because :func:`tune_up.cross_check_probe_moments` reports all
#: three. They span 2x on a Hann, so the choice is not cosmetic --
#: see :func:`stark_moments`.
MOMENT_WEIGHTINGS = ("rabi", "uniform", "coupling")


def rabi_angle(shape_fn, u) -> np.ndarray:
    r"""Accumulated Rabi angle ``theta(u)``, running ``0 -> pi`` across the pulse.

    ``theta(u) = 2 \int_0^t g dt'`` for a pulse whose total area is ``pi`` (a complete
    iSWAP), expressed on the normalized axis ``u`` in ``[-1, 1]``. Since
    ``g(t) ~ |eta(t)| = eta_peak sqrt(f(u))``, the area normalization cancels
    ``eta_peak`` and ``t_g`` and leaves a pure functional of the shape::

        theta(u) = pi * int_{-1}^{u} sqrt(f) du' / int_{-1}^{1} sqrt(f) du'

    This is the phase that makes :func:`stark_moments`'s ``"rabi"`` weighting work.

    Parameters
    ----------
    shape_fn : callable
        ``u -> |eta(u)|^2 / eta_peak^2``, vectorized.
    u : array_like
        Points in ``[-1, 1]``, ASCENDING, spanning the full pulse -- the cumulative
        integral is taken on this grid, so a partial span gives a partial angle.

    Returns
    -------
    ndarray
        ``theta(u)`` in radians, ``theta(-1) = 0`` and ``theta(1) = pi``.
    """
    u = np.asarray(u, dtype=float)
    s = np.sqrt(np.clip(np.asarray(shape_fn(u), dtype=float), 0.0, None))
    cum = np.concatenate([[0.0], np.cumsum(0.5 * (s[1:] + s[:-1]) * np.diff(u))])
    if not np.isfinite(cum[-1]) or cum[-1] <= 0.0:
        raise ValueError("rabi weighting needs a positive pulse area")
    return np.pi * cum / cum[-1]


def stark_moments(shape_fn, weighting: str = "rabi", n_quad: int = 4001) -> tuple:
    r"""``(M2, M4)``: how a SHAPED probe's chevron reports the Stark law.

    A constant probe at ``|eta|`` measures the law pointwise,
    ``delta = k2 |eta|^2 + k4 |eta|^4``. A shaped probe of PEAK ``eta*`` instead
    reports an average over its own envelope, and because the law is an even
    polynomial that average is DIAGONAL in ``{eta^2, eta^4}``::

        <delta>(eta*) = k2 M2 eta*^2 + k4 M4 eta*^4
        M2 = <f>,  M4 = <f^2>        f(u) = |eta(u)|^2 / eta*^2

    so each coefficient is scaled by its own moment with no mixing between orders.
    Recovering the pointwise law is then two divisions, ``k2 = K2/M2``,
    ``k4 = K4/M4`` -- which is what makes a shaped ladder usable at drives where a
    constant probe leaks too much to fit (see ``tune_up.rabi_shift_table``). An odd
    power or a non-polynomial term would mix orders and need a real deconvolution.

    Which average, though, is not a convention -- it is derivable, and the answer is
    neither of the obvious guesses. Take the two-level iSWAP subspace with coupling
    ``g(t)`` of total area ``pi`` and detuning ``D(t) = Delta + delta_stark(t)``. In
    the frame that follows the ideal rotation, ``D`` enters as ``D sigma_z / 2``,
    whose matrix element between the instantaneous state and its orthogonal partner
    carries a factor ``sin theta(t)``, ``theta`` being the accumulated Rabi angle
    (:func:`rabi_angle`). So to first order the error amplitude is
    ``-1/2 int D(t) sin theta(t) dt`` and the chevron peaks where it vanishes::

        Delta* = -<delta_stark>_w        w(t) = sin theta(t),  theta: 0 -> pi

    The weight vanishes at both pulse ends -- there the state sits at a pole of the
    Bloch sphere, where a ``z`` rotation does nothing -- and peaks at ``theta = pi/2``,
    the half-area point, which for a symmetric envelope is mid-gate where the envelope
    is near its peak. That is why ``M2`` comes out close to 1 rather than close to the
    time-average, and why weighting by time badly underestimates it:

    ============== ========== ========== =========================================
    Hann           M2         M4         weight
    ============== ========== ========== =========================================
    rabi           0.7115     0.5836     ``sin theta(t)``     <- derived, default
    coupling       0.6250     0.4922     ``|eta(t)|``
    uniform        0.3750     0.2734     ``1``
    ============== ========== ========== =========================================

    Measured, not argued: a two-level integration of the model above reproduces
    ``"rabi"`` to 5 decimal places at every drive and for each moment separately,
    while a cross-check against a constant probe on a real 3-mode device
    (``tune_up.cross_check_probe_moments``) put ``M2`` within ~4% of ``"rabi"``
    against 19% for ``"coupling"`` and a factor 2.1 for ``"uniform"``.

    Parameters
    ----------
    shape_fn : callable
        ``u -> |eta(u)|^2 / eta_peak^2`` on ``[-1, 1]``, vectorized.
    weighting : {"rabi", "uniform", "coupling"}
        Default ``"rabi"``, the derived weight. The other two are kept for
        comparison; they bracket it from below.
    n_quad : int, default 4001
        Trapezoid points for ``"rabi"``, which needs a cumulative integral and so
        cannot use the Gauss-Legendre path the other two take. Converged to <1e-6
        well below the default.

    Returns
    -------
    tuple of float
        ``(M2, M4)``, both in ``(0, 1]``.
    """
    if str(weighting) not in MOMENT_WEIGHTINGS:
        raise ValueError(f"weighting={weighting!r}: expected one of "
                         f"{list(MOMENT_WEIGHTINGS)}")
    if str(weighting) == "uniform":
        return (shape_mean_factor(shape_fn),
                shape_mean_factor(lambda u: np.asarray(shape_fn(u), float) ** 2))
    if str(weighting) == "coupling":
        norm = shape_mean_factor(lambda u: np.sqrt(np.asarray(shape_fn(u), float)))
        if not np.isfinite(norm) or norm <= 0.0:
            raise ValueError("coupling weighting needs a positive <|eta|>")
        return (shape_mean_factor(lambda u: np.asarray(shape_fn(u), float) ** 1.5) / norm,
                shape_mean_factor(lambda u: np.asarray(shape_fn(u), float) ** 2.5) / norm)
    u = np.linspace(-1.0, 1.0, max(int(n_quad), 101))
    f = np.clip(np.asarray(shape_fn(u), dtype=float), 0.0, None)
    w = np.sin(rabi_angle(shape_fn, u))
    norm = np.trapz(w, u)
    if not np.isfinite(norm) or norm <= 0.0:
        raise ValueError("rabi weighting needs a positive sin(theta) normalization")
    return (float(np.trapz(w * f, u) / norm), float(np.trapz(w * f * f, u) / norm))


def hann_stark_legendre(degree: int = 4) -> np.ndarray:
    """Legendre coefficients of the Hann Stark-tracking shape, truncated at `degree`.

    Parameters
    ----------
    degree : int, default 4
        Highest Legendre order to keep. See the module docstring for the measured
        truncation error at each degree.

    Returns
    -------
    ndarray
        ``a_0 .. a_degree`` (length ``degree + 1``).

    Raises
    ------
    ValueError
        If `degree` exceeds the tabulated range.
    """
    degree = int(degree)
    if degree < 0:
        raise ValueError("degree must be >= 0")
    if degree >= HANN_STARK_LEGENDRE.size:
        raise ValueError(
            f"degree {degree} exceeds the tabulated range "
            f"(max {HANN_STARK_LEGENDRE.size - 1}); the higher coefficients fall off "
            f"fast enough that this is almost certainly not what you want")
    return HANN_STARK_LEGENDRE[:degree + 1].copy()


def stark_chirp_seed(delta_stark_GHz: float, degree: int = 4,
                     pin_c0: bool = True) -> np.ndarray:
    """Chirp coefficients that track a Stark shift of `delta_stark_GHz`.

    Scales the Hann Stark shape so its MEAN equals `delta_stark_GHz` -- i.e. so the
    chirp reproduces, on average, the constant detuning a calibration already found
    -- and then (by default) removes that mean.

    Parameters
    ----------
    delta_stark_GHz : float
        The pulse-averaged Stark shift, in GHz. In practice this is the calibrated
        ``wp_offset_GHz`` at the operating amplitude, or
        ``stark_slope_from_map(...)['delta_stark_GHz']``.
    degree : int, default 4
        Legendre truncation order.
    pin_c0 : bool, default True
        Zero the k=0 coefficient. Strongly recommended: c_0 and ``wp_offset_GHz`` are
        exactly degenerate, so leaving both free gives an optimizer a flat direction
        and makes the saved operating point ambiguous. With c_0 pinned,
        ``chirp_coeffs_GHz`` carries pure STRUCTURE about a separately-calibrated
        carrier, and its norm is a direct measure of what the chirp bought.

    Returns
    -------
    ndarray
        Coefficients ``c_0 .. c_degree`` in GHz, ready for
        ``envelope.make_chirp`` / ``chirp_coeffs_GHz``.

    Examples
    --------
    >>> np.round(stark_chirp_seed(0.002, degree=4), 6)
    array([ 0.      ,  0.      , -0.0038  ,  0.      ,  0.002669])
    """
    a = hann_stark_legendre(degree)
    scale = float(delta_stark_GHz) / HANN_MEAN_FACTOR
    c = scale * a
    if pin_c0:
        c[0] = 0.0
    return c


def map_ridge(Z: np.ndarray, offsets_MHz: np.ndarray,
              amps: np.ndarray) -> np.ndarray:
    """The Stark ridge of a calibration map: best pump offset per amplitude row.

    ``calibration_map`` computes this information and throws it away -- it keeps only
    the single global argmax -- but the ridge is exactly the Stark shift as a function
    of drive, which is what a chirp seed needs. Recovering it costs nothing, since it
    is pure post-processing on the ``Z`` array every engine already returns.

    Each row's discrete argmax is refined by fitting a parabola through it and its two
    neighbours, so the ridge is not quantized to the offset grid.

    Parameters
    ----------
    Z : ndarray, shape (n_amp, n_off)
        Score (fidelity or transfer) over the grid.
    offsets_MHz : ndarray, shape (n_off,)
        Pump-offset axis (MHz).
    amps : ndarray, shape (n_amp,)
        Amplitude-scale axis; used only for its length.

    Returns
    -------
    ndarray, shape (n_amp,)
        Best offset (MHz) per amplitude row; NaN for an all-NaN row.
    """
    Z = np.asarray(Z, dtype=float)
    offsets_MHz = np.asarray(offsets_MHz, dtype=float)
    if Z.shape != (len(amps), offsets_MHz.size):
        raise ValueError(f"Z has shape {Z.shape}, expected "
                         f"{(len(amps), offsets_MHz.size)}")

    ridge = np.full(Z.shape[0], np.nan)
    for i, row in enumerate(Z):
        if np.all(np.isnan(row)):
            continue
        j = int(np.nanargmax(row))
        if 0 < j < row.size - 1 and np.all(np.isfinite(row[j - 1:j + 2])):
            y0, y1, y2 = row[j - 1], row[j], row[j + 1]
            denom = y0 - 2.0 * y1 + y2
            # denom == 0 is a flat top; denom > 0 means the "peak" is a local minimum
            # (a ragged row), and in both cases the vertex formula is meaningless.
            shift = 0.0 if denom >= 0 else 0.5 * (y0 - y2) / denom
            shift = float(np.clip(shift, -1.0, 1.0))
            step = offsets_MHz[j + 1] - offsets_MHz[j]
            ridge[i] = offsets_MHz[j] + shift * step
        else:
            ridge[i] = offsets_MHz[j]                    # railed at an edge
    return ridge


def stark_slope_from_map(result: Dict[str, Any],
                         amp_scale: Optional[float] = None) -> Dict[str, Any]:
    """Fit the calibration map's ridge to extract the Stark shift vs drive.

    The Stark shift is proportional to |eta|^2 and therefore to ``amp_scale**2``, so
    the ridge is fitted as ``offset_MHz = m * amp^2 + b``. The intercept is kept as a
    diagnostic rather than forced to zero: a large ``b`` means the map was built on a
    nominal offset that already absorbed part of the shift, or that the ridge railed
    against the scan window.

    Parameters
    ----------
    result : dict
        A ``calibration_map`` result (any engine): needs ``Z``, ``offsets_MHz``,
        ``amps``.
    amp_scale : float, optional
        Amplitude at which to report the shift. Defaults to the map's own optimum
        (``result['best']['amp_scale']``).

    Returns
    -------
    dict
        ``ridge_MHz`` (per-row), ``slope_MHz_per_amp2``, ``intercept_MHz``,
        ``amp_scale``, ``delta_stark_MHz`` / ``delta_stark_GHz`` (the fitted shift at
        `amp_scale`), and ``r2`` of the fit. A poor ``r2`` means the ridge is not
        Stark-dominated and the seed built from it should not be trusted.
    """
    Z = np.asarray(result["Z"], dtype=float)
    offsets = np.asarray(result["offsets_MHz"], dtype=float)
    amps = np.asarray(result["amps"], dtype=float)
    ridge = map_ridge(Z, offsets, amps)

    ok = np.isfinite(ridge)
    if ok.sum() < 3:
        raise ValueError("need at least 3 usable amplitude rows to fit the ridge")
    x = amps[ok] ** 2
    y = ridge[ok]
    m, b = np.polyfit(x, y, 1)
    resid = y - (m * x + b)
    ss_tot = float(np.sum((y - y.mean()) ** 2))
    r2 = 1.0 - float(np.sum(resid ** 2)) / ss_tot if ss_tot > 0 else float("nan")

    if amp_scale is None:
        amp_scale = float(result.get("best", {}).get("amp_scale", 1.0))
    delta_MHz = float(m * amp_scale ** 2 + b)
    return {"ridge_MHz": ridge, "slope_MHz_per_amp2": float(m),
            "intercept_MHz": float(b), "amp_scale": float(amp_scale),
            "delta_stark_MHz": delta_MHz, "delta_stark_GHz": delta_MHz * 1e-3,
            "r2": r2}


def seed_from_calibration_map(result: Dict[str, Any], degree: int = 4,
                              amp_scale: Optional[float] = None,
                              pin_c0: bool = True) -> np.ndarray:
    """Chirp seed straight from a calibration map. Convenience over the two steps.

    Parameters
    ----------
    result : dict
        A ``calibration_map`` result.
    degree : int, default 4
        Legendre truncation order.
    amp_scale : float, optional
        Operating amplitude; defaults to the map's optimum.
    pin_c0 : bool, default True
        See :func:`stark_chirp_seed`.

    Returns
    -------
    ndarray
        Chirp coefficients (GHz).
    """
    fit = stark_slope_from_map(result, amp_scale=amp_scale)
    return stark_chirp_seed(fit["delta_stark_GHz"], degree=degree, pin_c0=pin_c0)


def describe_seed(coeffs: Sequence[float], delta_stark_GHz: float) -> str:
    """One-line summary of a seed and the shift it was built to track."""
    nz = ", ".join(f"c{k}={c:+.5f}" for k, c in enumerate(coeffs) if c)
    return (f"stark-chirp seed for delta_stark={delta_stark_GHz * 1e3:+.3f} MHz: "
            f"[{nz or 'all zero'}] GHz")
